parameters:
  jobrouter_process.widget.transfersPerDay.numberOfDays: 14
  jobrouter_process.widget.typeOfInstanceStarts.numberOfDays: 14

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterProcess\:
    resource: '../Classes/*'

  querybuilder.tx_jobrouterprocess_domain_model_transfer:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory: ['@TYPO3\CMS\Core\Database\ConnectionPool', 'getQueryBuilderForTable']
    arguments: ['tx_jobrouterprocess_domain_model_transfer']

  Brotkrueml\JobRouterProcess\Command\CleanUpTransfersCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:process:cleanuptransfers'
        schedulable: true

  Brotkrueml\JobRouterProcess\Command\StartCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:process:start'
        schedulable: true

  Brotkrueml\JobRouterProcess\Domain\Repository\QueryBuilder\TransferRepository:
    arguments:
      $queryBuilder: '@querybuilder.tx_jobrouterprocess_domain_model_transfer'

  Brotkrueml\JobRouterProcess\Dashboard\Provider\TransfersPerDayDataProvider:
    calls:
      - [setNumberOfDays, ['%jobrouter_process.widget.transfersPerDay.numberOfDays%']]

  Brotkrueml\JobRouterProcess\Dashboard\Provider\TransferTypeChartDataProvider:
    calls:
      - [setNumberOfDays, ['%jobrouter_process.widget.typeOfInstanceStarts.numberOfDays%']]
