services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterProcess\:
    resource: '../Classes/*'

  querybuilder.tx_jobrouterprocess_domain_model_transfer:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory: ['@TYPO3\CMS\Core\Database\ConnectionPool', 'getQueryBuilderForTable']
    arguments: ['tx_jobrouterprocess_domain_model_transfer']

  Brotkrueml\JobRouterProcess\Dashboard\Provider\TransferTypeChartDataProvider:
    arguments:
      $queryBuilder: '@querybuilder.tx_jobrouterprocess_domain_model_transfer'
