parameters:
  jobrouter_process.widget.transfersPerDay.numberOfDays: 14
  jobrouter_process.widget.typeOfInstanceStarts.numberOfDays: 14

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterProcess\:
    resource: '../Classes/*'

  querybuilder.tx_jobrouterprocess_domain_model_transfer:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory: ['@TYPO3\CMS\Core\Database\ConnectionPool', 'getQueryBuilderForTable']
    arguments: ['tx_jobrouterprocess_domain_model_transfer']

  Brotkrueml\JobRouterProcess\Command\CleanUpTransfersCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:process:cleanuptransfers'
        schedulable: true

  Brotkrueml\JobRouterProcess\Command\StartCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:process:start'
        schedulable: true

  Brotkrueml\JobRouterProcess\Dashboard\Provider\TransfersPerDayDataProvider:
    calls:
      - [setNumberOfDays, ['%jobrouter_process.widget.transfersPerDay.numberOfDays%']]

  Brotkrueml\JobRouterProcess\Dashboard\Provider\TransferTypeChartDataProvider:
    calls:
      - [setNumberOfDays, ['%jobrouter_process.widget.typeOfInstanceStarts.numberOfDays%']]

  Brotkrueml\JobRouterProcess\Domain\Repository\QueryBuilder\TransferRepository:
    arguments:
      $queryBuilder: '@querybuilder.tx_jobrouterprocess_domain_model_transfer'

  Brotkrueml\JobRouterProcess\Domain\VariableResolver\JobRouterLanguageVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-process/jobrouter-language-variable-resolver'
        event: Brotkrueml\JobRouterProcess\Event\ResolveFinisherVariableEvent

  Brotkrueml\JobRouterProcess\Domain\VariableResolver\LanguageVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-process/language-variable-resolver'
        event: Brotkrueml\JobRouterProcess\Event\ResolveFinisherVariableEvent

  Brotkrueml\JobRouterProcess\Domain\VariableResolver\LocalisedLabelVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-process/localised-label-variable-resolver'
        event: Brotkrueml\JobRouterProcess\Event\ResolveFinisherVariableEvent

  Brotkrueml\JobRouterProcess\Domain\VariableResolver\TransferIdentifierVariableResolver:
    tags:
      - name: event.listener
        identifier: 'jobrouter-process/transfer-identifier-variable-resolver'
        event: Brotkrueml\JobRouterProcess\Event\ResolveFinisherVariableEvent

  Brotkrueml\JobRouterProcess\EventListener\ToolbarItemProvider:
    tags:
      - name: event.listener
        identifier: 'jobrouter-process/toolbar-item-provider'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent

  Brotkrueml\JobRouterProcess\Transfer\Deleter:
    arguments:
      $queryBuilder: '@querybuilder.tx_jobrouterprocess_domain_model_transfer'
